### ISSUE TITLE
Proof of Theorem 2 

### ISSUE THREAD

**Issue by HolmesShuan** [MAC-AutoML/ITPruner#1]
```python
import torch
import torch.nn as nn

m = 121
n = 128
k = 512

Y = torch.randn(m, n)
U = torch.randn(m, m)
X = torch.randn(m, k)

nn.init.orthogonal_(U)

print("||U^TU||_F=", torch.norm(torch.matmul(U, torch.transpose(U, 0, 1)), p='fro').item())

print("||Y^TX||_F=", torch.norm(torch.matmul(torch.transpose(Y, 0, 1), X)).item())
print("||Y^TUX||_F=", torch.norm(torch.matmul(torch.matmul(torch.transpose(Y, 0, 1), U), X)).item())

print("||X||_F=", torch.norm(X).item())
print("||UX||_F=", torch.norm(torch.matmul(U, X)).item())
```
```python
||U^TU||_F= 11.0
||Y^TX||_F= 2809.56884765625
||Y^TUX||_F= 2826.705078125
||X||_F= 248.32562255859375
||UX||_F= 248.325439453125
```

**Comment by BobxmuMa** [comment]
> ```python
> import torch
> import torch.nn as nn
> 
> m = 121
> n = 128
> k = 512
> 
> Y = torch.randn(m, n)
> U = torch.randn(m, m)
> X = torch.randn(m, k)
> 
> nn.init.orthogonal_(U)
> 
> print("||U^TU||_F=", torch.norm(torch.matmul(U, torch.transpose(U, 0, 1)), p='fro').item())
> 
> print("||Y^TX||_F=", torch.norm(torch.matmul(torch.transpose(Y, 0, 1), X)).item())
> print("||Y^TUX||_F=", torch.norm(torch.matmul(torch.matmul(torch.transpose(Y, 0, 1), U), X)).item())
> 
> print("||X||_F=", torch.norm(X).item())
> print("||UX||_F=", torch.norm(torch.matmul(U, X)).item())
> ```
> 
> ```python
> ||U^TU||_F= 11.0
> ||Y^TX||_F= 2809.56884765625
> ||Y^TUX||_F= 2826.705078125
> ||X||_F= 248.32562255859375
> ||UX||_F= 248.325439453125
> ```

Firstly, thank you very much for your carefulness. The orthogonal transformation on X,Y is right multiplicative in our code, i.e. XU,YU, which is an orthogonal transformation of features not samples. This will ensure the orthogonality invariance and we will also correct this in our paper.

**Comment by zhengxiawu** [comment]
As @BobxmuMa mentioned before, we made a mistake in theorem 2 of the Arxiv version. Specifically the original version is nHSIC_{linear}(UX, Y) = nHSIC_{linear}(X, Y). And the corrected version is nHSIC_{linear}(XU, Y) = nHSIC_{linear}(X, Y). Thanks again for your comments, we had revised this typos in our newest version, which will be uploaded in Arxiv.
